# Generated by Django 3.2.3 on 2021-07-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
                ('star', models.IntegerField()),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('kind', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('grape_type1', models.CharField(max_length=50)),
                ('grape_type2', models.CharField(max_length=50)),
                ('explain', models.CharField(max_length=200)),
                ('taste1', models.CharField(max_length=50)),
                ('taste2', models.CharField(max_length=50)),
                ('alchol', models.FloatField()),
                ('dry', models.FloatField()),
                ('body', models.FloatField()),
                ('tannin', models.FloatField()),
            ],
        ),
    ]
